//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoseHillSolutions.KeyMapper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point KeyboardFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["KeyboardFormLocation"]));
            }
            set {
                this["KeyboardFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardFormHasNumberPad {
            get {
                return ((bool)(this["KeyboardFormHasNumberPad"]));
            }
            set {
                this["KeyboardFormHasNumberPad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserHasSavedSettings {
            get {
                return ((bool)(this["UserHasSavedSettings"]));
            }
            set {
                this["UserHasSavedSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int KeyboardFormWidth {
            get {
                return ((int)(this["KeyboardFormWidth"]));
            }
            set {
                this["KeyboardFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ColourListFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["ColourListFormLocation"]));
            }
            set {
                this["ColourListFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardFormColourMapFormOpen {
            get {
                return ((bool)(this["KeyboardFormColourMapFormOpen"]));
            }
            set {
                this["KeyboardFormColourMapFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MappingListFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MappingListFormLocation"]));
            }
            set {
                this["MappingListFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardFormHasMacKeyboard {
            get {
                return ((bool)(this["KeyboardFormHasMacKeyboard"]));
            }
            set {
                this["KeyboardFormHasMacKeyboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeyboardFormHasMappingListFormOpen {
            get {
                return ((bool)(this["KeyboardFormHasMappingListFormOpen"]));
            }
            set {
                this["KeyboardFormHasMappingListFormOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditMappingFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["EditMappingFormLocation"]));
            }
            set {
                this["EditMappingFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MappingListFormWidth {
            get {
                return ((int)(this["MappingListFormWidth"]));
            }
            set {
                this["MappingListFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ColourEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["ColourEditorLocation"]));
            }
            set {
                this["ColourEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastMappingsFilter {
            get {
                return ((int)(this["LastMappingsFilter"]));
            }
            set {
                this["LastMappingsFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelpFormAtAtStartup {
            get {
                return ((bool)(this["ShowHelpFormAtAtStartup"]));
            }
            set {
                this["ShowHelpFormAtAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point HelpFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["HelpFormLocation"]));
            }
            set {
                this["HelpFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HelpFormOpen {
            get {
                return ((bool)(this["HelpFormOpen"]));
            }
            set {
                this["HelpFormOpen"] = value;
            }
        }
    }
}
