//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyMapper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class UserColours : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserColours defaultInstance = ((UserColours)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserColours())));
        
        public static UserColours Default {
            get {
                return defaultInstance;
            }
        }
    }
}
